In [1]:
import numpy as np

In [45]:
jobs = np.array([[1995,856,564,260], [1982,800,520,204], [1920,878,587,290]])

In [46]:
jobs

array([[1995,  856,  564,  260],
       [1982,  800,  520,  204],
       [1920,  878,  587,  290]])

In [47]:
machines = np.array([1,2,3])

In [48]:
machines

array([1, 2, 3])

In [24]:
jobs[0]

array([1995,  856,  564,  260])

In [26]:
jobs[0] = np.append(jobs[0],np.sum(jobs[0]))

ValueError: could not broadcast input array from shape (5) into shape (4)

In [27]:
len(jobs[0])

4

In [43]:
temp = []
for i in range(len(jobs)):
   temp = np.array(np.append(jobs[i],np.sum(jobs[i])))

In [44]:
temp

array([0.])

In [50]:
times = np.array([])

In [51]:
times

array([], dtype=float64)

In [52]:
for i in range(len(jobs)):
    times = np.append(times,np.sum(jobs[i]))

In [53]:
times

array([3675., 3506., 3675.])

In [57]:
np.max(times)

3675.0

In [58]:
np.argmax(times)

0

In [60]:
times[0]

3675.0

In [61]:
jobs[0]

array([1995,  856,  564,  260])

In [ ]:
costBeta = self.workload[np.argmax(self.workload)] # find max workload across machines, faster than np.max(self.workload) 
        # if new feasible solution is worse then go back, otherwise stay
        if costBeta > costAlpha:
            for (job, machine) in zip(jobs, initialMachines):
                self.switchMachine(job, machine)
            self.costTrajectory.append(costAlpha)
        else:
            self.cost = costBeta
            self.costTrajectory.append(costBeta)

In [73]:
jobs

array([[1995,  856,  564,  260],
       [1982,  800,  520,  204],
       [1920,  878,  587,  290]])

In [65]:
temp = []
for i in range(len(jobs)):
    for j in range(len(jobs[i])):
        temp.append(jobs[i][j])
        

In [66]:
temp

[1995, 856, 564, 260, 1982, 800, 520, 204, 1920, 878, 587, 290]

In [72]:
costAlpha = 0

In [79]:
costBeta = np.argmax(times)

In [91]:
np.argmin(times)

1

In [81]:
times[costBeta]

3675.0

In [ ]:
if costBeta > costAlpha:
    for (job, machine) in zip(jobs, initialMachines):
        self.switchMachine(job, machine)
        self.costTrajectory.append(costAlpha)
    else:
        self.cost = costBeta
        self.costTrajectory.append(costBeta)

In [77]:
for (job, machine) in zip(jobs, machines):
    print(job,machine)

[1995  856  564  260] 1
[1982  800  520  204] 2
[1920  878  587  290] 3


In [83]:
times

array([3675., 3506., 3675.])

In [90]:
times[costBeta] - jobs[np.argmax(times)][np.argmax(jobs[np.argmax(times)])] + jobs[np.argmax(times)+1][np.argmax(jobs[np.argmax(times)])]

3662.0

In [88]:
print(jobs[np.argmax(times)][np.argmax(jobs[np.argmax(times)])])
print(jobs[np.argmax(times)+1][np.argmax(jobs[np.argmax(times)])])




        

1995
1982


workload <- times
p <- jobs
machine <- machine

In [ ]:
def switchMachine(self, job, toMachine):
    self.workload[self.machine[job]] = machine[job] -p[job]
    self.machine[job] = toMachine
    self.workload[toMachine] += p[job]

In [74]:
A = [1,2,3]
B = [4,5,6]

for (i,j) in zip(A,B):
    print(i,j)

1 4
2 5
3 6


In [92]:
allowableTime = 1
m = 4
p = [3, 2, 4, 1, 3, 3, 6, 2, 5, 4, 6]

In [ ]:
# work on putting p into 4 machines
# get python to do the swaps
# try to find an optimal solution

In [102]:
workload = np.zeros(m)

In [103]:
workload

array([0., 0., 0., 0.])

In [ ]:
# write a loop (ie for i in range(len(p)) ) to put the jobs in p into workloads
# first, manually swap the element to move toward optimality - workload[j] - p[k],  workload[i] + p[k]


In [100]:
workload[0] = p[0]